name: Maven on Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile  # Path to your Dockerfile if needed

    - name: Build and run Maven container
      run: |
        docker run --rm maven:latest mvn --version
