name: Docker Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 8080:8080  # If you need to expose any ports

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Maven version
        run: |
          docker run maven mvn --version

